### ISSUE TITLE
Handling 'Unhandled Interrupts' blocks interface

### ISSUE THREAD

**Issue by doewie** [jeelabs/folie#42]
I ran into following situation with setup:
Folie2 on RasPi -> BluePill/SerPlus -> JeeNode Zero

For some reason, which unfortunately i can't replay, the Jeenode Zero continuously sends 'Unhandled Interrupt 00000003 !'. Reset doesn't help because history repeats. I think the only way to come out of this loop is to put the Jeenode Zero in bootmode and reflash, but with this incoming datastream it's not possible to submit a new !u <nn> command from Folie2. 

I found following workaround:
•	Disconnect power to the Jeenode Zero
•	Start uploading a *.bin file from Folie2 ( f.i. Mecrisp)
•	Reconnect power to the JeeNode Zero. 
Now communication starts and the new Mecrisp is loaded and works!!

Maybe Folie2 can force a bootmode if this datastream of Unhandled Interupts is received?

**Comment by jcw** [comment]
Glad you found a workaround! - This infinite loop can have several causes, and is probably worth figuring out in much more detail. Recent `board.fs` files include `../flib/mecrisp/calltrace.fs` which turn such errors into a stack trace + hang, which is a lot more useful.

Maybe the best thing now is to rename this issue slightly and leave it open, to collect more examples and try and get a grip on what's causing them?

**Comment by doewie** [comment]
If calltrace.fs indeed always catches these unhandled interrupts then maybe we can close this issue?

**Comment by jcw** [comment]
Yes, I never get this anymore - the trick is to add [this line](https://github.com/jeelabs/embello/blob/master/explore/1608-forth/g6s/board.fs#L29) to `init`:

    ['] ct-irq irq-fault !

Ok, I'll close this issue. But there is still a problem whereby a `cornerstone` is defined in RAM instead of flash, which then generates an exception when called. Let's just keep an eye on it and create a new issue for it when we have a better view of what's going on.
